spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.ivdtjwkrhtmvhueaemru
    password: NQApqTqbPycGKcz8
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0
      maxLifetime: 180000
      connectionTimeout: 30000
      validationTimeout: 5000
      connection-test-query: SELECT 1
      minimumIdle: 2
      maximumPoolSize: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection.release_mode: after_transaction

  web:
    cors:
      allowed-origins: 
        - http://localhost:5173
        - https://autoancillarieslimited.netlify.app
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true

app:
  jwt:
    secret: urSFJGdbsp4NTzMGZmssNy7wm2mLjNSt
    expirationMs: 604800000

app.frontend.url: http://localhost:5173

server:
  port: 8080

supabase:
  url: https://ivdtjwkrhtmvhueaemru.supabase.co
  anon-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZHRqd2tyaHRtdmh1ZWFlbXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4NTQzOTksImV4cCI6MjA5NzQzMDM5OX0.d_z0jKzOKuONqx70d2Q7rhSwGvPehS4OZLySn-5kKJs